version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Validating DAGs"
      - python -m py_compile dags/*.py || true

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - dags/**/*
    - sql/**/*
